"""Add referee analytics tables

Revision ID: 1a24d83df445
Revises: 8fecb9d4f286
Create Date: 2025-07-11 21:45:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a24d83df445'
down_revision: Union[str, Sequence[str], None] = '8fecb9d4f286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create referees table
    op.create_table('referees',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('email', sa.String(length=200), nullable=False),
        sa.Column('institution', sa.String(length=300), nullable=True),
        sa.Column('h_index', sa.Integer(), nullable=True),
        sa.Column('years_experience', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('active', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_referee_email', 'referees', ['email'], unique=True)
    op.create_index('idx_referee_institution', 'referees', ['institution'], unique=False)
    op.create_index('idx_referee_h_index', 'referees', ['h_index'], unique=False)
    op.create_index('idx_referee_active', 'referees', ['active'], unique=False)
    op.create_index(op.f('ix_referees_email'), 'referees', ['email'], unique=False)
    op.create_index(op.f('ix_referees_name'), 'referees', ['name'], unique=False)
    
    # Create referee_expertise table
    op.create_table('referee_expertise',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('referee_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('expertise_area', sa.String(length=100), nullable=False),
        sa.Column('confidence_score', sa.Float(), nullable=False),
        sa.Column('evidence_count', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.CheckConstraint('confidence_score >= 0.0 AND confidence_score <= 1.0', name='check_confidence_range'),
        sa.CheckConstraint('evidence_count >= 0', name='check_evidence_count'),
        sa.ForeignKeyConstraint(['referee_id'], ['referees.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_expertise_referee_area', 'referee_expertise', ['referee_id', 'expertise_area'], unique=False)
    op.create_index('idx_expertise_confidence', 'referee_expertise', ['confidence_score'], unique=False)
    op.create_index(op.f('ix_referee_expertise_expertise_area'), 'referee_expertise', ['expertise_area'], unique=False)
    op.create_index(op.f('ix_referee_expertise_referee_id'), 'referee_expertise', ['referee_id'], unique=False)
    
    # Create manuscripts table
    op.create_table('manuscripts',
        sa.Column('id', sa.String(length=100), nullable=False),
        sa.Column('journal_code', sa.String(length=10), nullable=False),
        sa.Column('title', sa.String(length=500), nullable=True),
        sa.Column('abstract', sa.Text(), nullable=True),
        sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column('research_area', sa.String(length=200), nullable=True),
        sa.Column('submission_date', sa.DateTime(), nullable=True),
        sa.Column('decision_date', sa.DateTime(), nullable=True),
        sa.Column('final_decision', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_manuscript_journal', 'manuscripts', ['journal_code'], unique=False)
    op.create_index('idx_manuscript_research_area', 'manuscripts', ['research_area'], unique=False)
    op.create_index('idx_manuscript_decision', 'manuscripts', ['final_decision'], unique=False)
    op.create_index('idx_manuscript_submission_date', 'manuscripts', ['submission_date'], unique=False)
    
    # Create review_history table
    op.create_table('review_history',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('referee_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('manuscript_id', sa.String(length=100), nullable=False),
        sa.Column('invited_date', sa.DateTime(), nullable=False),
        sa.Column('responded_date', sa.DateTime(), nullable=True),
        sa.Column('due_date', sa.DateTime(), nullable=True),
        sa.Column('submitted_date', sa.DateTime(), nullable=True),
        sa.Column('decision', sa.String(length=20), nullable=True),
        sa.Column('quality_score', sa.Float(), nullable=True),
        sa.Column('report_length', sa.Integer(), nullable=True),
        sa.Column('reminder_count', sa.Integer(), nullable=False),
        sa.Column('follow_up_count', sa.Integer(), nullable=False),
        sa.Column('editor_notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.CheckConstraint('quality_score IS NULL OR (quality_score >= 1.0 AND quality_score <= 10.0)', name='check_quality_range'),
        sa.CheckConstraint('reminder_count >= 0', name='check_reminder_count'),
        sa.CheckConstraint('follow_up_count >= 0', name='check_followup_count'),
        sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['referee_id'], ['referees.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_review_referee_manuscript', 'review_history', ['referee_id', 'manuscript_id'], unique=False)
    op.create_index('idx_review_invited_date', 'review_history', ['invited_date'], unique=False)
    op.create_index('idx_review_decision', 'review_history', ['decision'], unique=False)
    op.create_index('idx_review_quality', 'review_history', ['quality_score'], unique=False)
    op.create_index(op.f('ix_review_history_manuscript_id'), 'review_history', ['manuscript_id'], unique=False)
    op.create_index(op.f('ix_review_history_referee_id'), 'review_history', ['referee_id'], unique=False)
    op.create_index(op.f('ix_review_history_invited_date'), 'review_history', ['invited_date'], unique=False)
    op.create_index(op.f('ix_review_history_submitted_date'), 'review_history', ['submitted_date'], unique=False)
    
    # Create referee_analytics_cache table
    op.create_table('referee_analytics_cache',
        sa.Column('referee_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('metrics_json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column('calculated_at', sa.DateTime(), nullable=False),
        sa.Column('valid_until', sa.DateTime(), nullable=False),
        sa.Column('data_version', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['referee_id'], ['referees.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('referee_id')
    )
    op.create_index('idx_analytics_cache_valid', 'referee_analytics_cache', ['valid_until'], unique=False)
    op.create_index('idx_analytics_cache_calculated', 'referee_analytics_cache', ['calculated_at'], unique=False)
    
    # Create referee_metrics_history table
    op.create_table('referee_metrics_history',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('referee_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('metric_date', sa.Date(), nullable=False),
        sa.Column('overall_score', sa.Float(), nullable=True),
        sa.Column('speed_score', sa.Float(), nullable=True),
        sa.Column('quality_score', sa.Float(), nullable=True),
        sa.Column('reliability_score', sa.Float(), nullable=True),
        sa.Column('expertise_score', sa.Float(), nullable=True),
        sa.Column('current_reviews', sa.Integer(), nullable=False),
        sa.Column('monthly_average', sa.Float(), nullable=True),
        sa.Column('burnout_risk', sa.Float(), nullable=True),
        sa.Column('speed_percentile', sa.Float(), nullable=True),
        sa.Column('quality_percentile', sa.Float(), nullable=True),
        sa.Column('reliability_percentile', sa.Float(), nullable=True),
        sa.Column('overall_percentile', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.CheckConstraint('overall_score IS NULL OR (overall_score >= 0.0 AND overall_score <= 1.0)', name='check_overall_score_range'),
        sa.CheckConstraint('speed_score IS NULL OR (speed_score >= 0.0 AND speed_score <= 1.0)', name='check_speed_score_range'),
        sa.CheckConstraint('quality_score IS NULL OR (quality_score >= 0.0 AND quality_score <= 1.0)', name='check_quality_score_range'),
        sa.CheckConstraint('reliability_score IS NULL OR (reliability_score >= 0.0 AND reliability_score <= 1.0)', name='check_reliability_score_range'),
        sa.CheckConstraint('current_reviews >= 0', name='check_current_reviews'),
        sa.ForeignKeyConstraint(['referee_id'], ['referees.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_metrics_history_referee_date', 'referee_metrics_history', ['referee_id', 'metric_date'], unique=True)
    op.create_index('idx_metrics_history_date', 'referee_metrics_history', ['metric_date'], unique=False)
    op.create_index('idx_metrics_history_overall_score', 'referee_metrics_history', ['overall_score'], unique=False)
    
    # Create journal_specific_metrics table
    op.create_table('journal_specific_metrics',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('referee_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('journal_code', sa.String(length=10), nullable=False),
        sa.Column('reviews_completed', sa.Integer(), nullable=False),
        sa.Column('acceptance_rate', sa.Float(), nullable=False),
        sa.Column('avg_quality_score', sa.Float(), nullable=True),
        sa.Column('avg_review_time_days', sa.Float(), nullable=True),
        sa.Column('familiarity_score', sa.Float(), nullable=False),
        sa.Column('first_review_date', sa.DateTime(), nullable=True),
        sa.Column('last_review_date', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.CheckConstraint('reviews_completed >= 0', name='check_reviews_completed'),
        sa.CheckConstraint('acceptance_rate >= 0.0 AND acceptance_rate <= 1.0', name='check_acceptance_rate'),
        sa.CheckConstraint('avg_quality_score IS NULL OR (avg_quality_score >= 1.0 AND avg_quality_score <= 10.0)', name='check_avg_quality'),
        sa.CheckConstraint('familiarity_score >= 0.0 AND familiarity_score <= 1.0', name='check_familiarity_score'),
        sa.ForeignKeyConstraint(['referee_id'], ['referees.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_journal_metrics_referee_journal', 'journal_specific_metrics', ['referee_id', 'journal_code'], unique=True)
    op.create_index('idx_journal_metrics_journal', 'journal_specific_metrics', ['journal_code'], unique=False)
    op.create_index('idx_journal_metrics_familiarity', 'journal_specific_metrics', ['familiarity_score'], unique=False)
    op.create_index(op.f('ix_journal_specific_metrics_last_review_date'), 'journal_specific_metrics', ['last_review_date'], unique=False)
    
    # Create performance_tiers table
    op.create_table('performance_tiers',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('referee_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('tier', sa.String(length=30), nullable=False),
        sa.Column('tier_percentile', sa.Float(), nullable=False),
        sa.Column('tier_score', sa.Float(), nullable=False),
        sa.Column('assessment_date', sa.Date(), nullable=False),
        sa.Column('sample_size', sa.Integer(), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=False),
        sa.Column('peer_group_size', sa.Integer(), nullable=True),
        sa.Column('journal_context', sa.String(length=10), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.CheckConstraint('tier_percentile >= 0.0 AND tier_percentile <= 100.0', name='check_tier_percentile'),
        sa.CheckConstraint('tier_score >= 0.0 AND tier_score <= 10.0', name='check_tier_score'),
        sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='check_confidence'),
        sa.CheckConstraint('sample_size > 0', name='check_sample_size'),
        sa.ForeignKeyConstraint(['referee_id'], ['referees.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_performance_tier_referee_date', 'performance_tiers', ['referee_id', 'assessment_date'], unique=False)
    op.create_index('idx_performance_tier_tier', 'performance_tiers', ['tier'], unique=False)
    op.create_index('idx_performance_tier_percentile', 'performance_tiers', ['tier_percentile'], unique=False)
    op.create_index(op.f('ix_performance_tiers_assessment_date'), 'performance_tiers', ['assessment_date'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_performance_tiers_assessment_date'), table_name='performance_tiers')
    op.drop_index('idx_performance_tier_percentile', table_name='performance_tiers')
    op.drop_index('idx_performance_tier_tier', table_name='performance_tiers')
    op.drop_index('idx_performance_tier_referee_date', table_name='performance_tiers')
    op.drop_table('performance_tiers')
    op.drop_index(op.f('ix_journal_specific_metrics_last_review_date'), table_name='journal_specific_metrics')
    op.drop_index('idx_journal_metrics_familiarity', table_name='journal_specific_metrics')
    op.drop_index('idx_journal_metrics_journal', table_name='journal_specific_metrics')
    op.drop_index('idx_journal_metrics_referee_journal', table_name='journal_specific_metrics')
    op.drop_table('journal_specific_metrics')
    op.drop_index('idx_metrics_history_overall_score', table_name='referee_metrics_history')
    op.drop_index('idx_metrics_history_date', table_name='referee_metrics_history')
    op.drop_index('idx_metrics_history_referee_date', table_name='referee_metrics_history')
    op.drop_table('referee_metrics_history')
    op.drop_index('idx_analytics_cache_calculated', table_name='referee_analytics_cache')
    op.drop_index('idx_analytics_cache_valid', table_name='referee_analytics_cache')
    op.drop_table('referee_analytics_cache')
    op.drop_index(op.f('ix_review_history_submitted_date'), table_name='review_history')
    op.drop_index(op.f('ix_review_history_invited_date'), table_name='review_history')
    op.drop_index(op.f('ix_review_history_referee_id'), table_name='review_history')
    op.drop_index(op.f('ix_review_history_manuscript_id'), table_name='review_history')
    op.drop_index('idx_review_quality', table_name='review_history')
    op.drop_index('idx_review_decision', table_name='review_history')
    op.drop_index('idx_review_invited_date', table_name='review_history')
    op.drop_index('idx_review_referee_manuscript', table_name='review_history')
    op.drop_table('review_history')
    op.drop_index('idx_manuscript_submission_date', table_name='manuscripts')
    op.drop_index('idx_manuscript_decision', table_name='manuscripts')
    op.drop_index('idx_manuscript_research_area', table_name='manuscripts')
    op.drop_index('idx_manuscript_journal', table_name='manuscripts')
    op.drop_table('manuscripts')
    op.drop_index(op.f('ix_referee_expertise_referee_id'), table_name='referee_expertise')
    op.drop_index(op.f('ix_referee_expertise_expertise_area'), table_name='referee_expertise')
    op.drop_index('idx_expertise_confidence', table_name='referee_expertise')
    op.drop_index('idx_expertise_referee_area', table_name='referee_expertise')
    op.drop_table('referee_expertise')
    op.drop_index(op.f('ix_referees_name'), table_name='referees')
    op.drop_index(op.f('ix_referees_email'), table_name='referees')
    op.drop_index('idx_referee_active', table_name='referees')
    op.drop_index('idx_referee_h_index', table_name='referees')
    op.drop_index('idx_referee_institution', table_name='referees')
    op.drop_index('idx_referee_email', table_name='referees')
    op.drop_table('referees')
    # ### end Alembic commands ###