"""Initial ECC schema

Revision ID: 1a4f4345c3e1
Revises: 
Create Date: 2025-08-22 20:14:21.097613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a4f4345c3e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manuscripts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('journal_id', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('current_status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'AWAITING_REFEREE_REPORTS', 'AWAITING_DECISION', 'REVISION_REQUESTED', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', name='manuscriptstatus'), nullable=False),
    sa.Column('submission_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('figure_count', sa.Integer(), nullable=True),
    sa.Column('table_count', sa.Integer(), nullable=True),
    sa.Column('funding_information', sa.Text(), nullable=True),
    sa.Column('conflict_of_interest', sa.Text(), nullable=True),
    sa.Column('data_availability', sa.Text(), nullable=True),
    sa.Column('msc_codes', sa.JSON(), nullable=False),
    sa.Column('topic_area', sa.String(length=200), nullable=True),
    sa.Column('editor_assigned', sa.String(length=200), nullable=True),
    sa.Column('manuscript_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal_id', 'external_id', name='uq_journal_manuscript')
    )
    op.create_index(op.f('ix_manuscripts_current_status'), 'manuscripts', ['current_status'], unique=False)
    op.create_index(op.f('ix_manuscripts_external_id'), 'manuscripts', ['external_id'], unique=False)
    op.create_index(op.f('ix_manuscripts_journal_id'), 'manuscripts', ['journal_id'], unique=False)
    op.create_table('ai_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('manuscript_id', sa.UUID(), nullable=False),
    sa.Column('analysis_type', sa.Enum('DESK_REJECTION', 'REFEREE_RECOMMENDATION', 'REPORT_SYNTHESIS', 'PLAGIARISM_CHECK', 'CONFLICT_DETECTION', name='analysistype'), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('human_review', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('manuscript_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_timestamp'), 'audit_events', ['timestamp'], unique=False)
    op.create_table('authors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('manuscript_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('orcid', sa.String(length=50), nullable=True),
    sa.Column('institution', sa.String(length=500), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('is_corresponding', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('manuscript_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('MANUSCRIPT', 'COVER_LETTER', 'REFEREE_REPORT', 'DECISION_LETTER', 'REVISION', 'SUPPLEMENTARY', name='documenttype'), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('checksum', sa.String(length=100), nullable=False),
    sa.Column('uploaded_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('manuscript_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('institution', sa.String(length=500), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('INVITED', 'AGREED', 'DECLINED', 'REPORT_SUBMITTED', 'OVERDUE', 'CANCELLED', name='refereestatus'), nullable=False),
    sa.Column('invited_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agreed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('report_due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('report_submitted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expertise_score', sa.Float(), nullable=True),
    sa.Column('conflict_of_interest', sa.Boolean(), nullable=False),
    sa.Column('historical_performance', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status_changes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('manuscript_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'AWAITING_REFEREE_REPORTS', 'AWAITING_DECISION', 'REVISION_REQUESTED', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', name='manuscriptstatus'), nullable=False),
    sa.Column('to_status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'AWAITING_REFEREE_REPORTS', 'AWAITING_DECISION', 'REVISION_REQUESTED', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', name='manuscriptstatus'), nullable=False),
    sa.Column('changed_by', sa.String(length=200), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('manuscript_id', sa.UUID(), nullable=False),
    sa.Column('referee_id', sa.UUID(), nullable=False),
    sa.Column('recommendation', sa.String(length=100), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('major_comments', sa.Text(), nullable=False),
    sa.Column('minor_comments', sa.Text(), nullable=False),
    sa.Column('confidential_comments', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('submitted_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.ForeignKeyConstraint(['referee_id'], ['referees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_table('status_changes')
    op.drop_table('referees')
    op.drop_table('files')
    op.drop_table('authors')
    op.drop_index(op.f('ix_audit_events_timestamp'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('ai_analyses')
    op.drop_index(op.f('ix_manuscripts_journal_id'), table_name='manuscripts')
    op.drop_index(op.f('ix_manuscripts_external_id'), table_name='manuscripts')
    op.drop_index(op.f('ix_manuscripts_current_status'), table_name='manuscripts')
    op.drop_table('manuscripts')
    # ### end Alembic commands ###
