"""Add AI analysis tables

Revision ID: 1be8a3b5d355
Revises: 1d6ca9dbb698
Create Date: 2025-07-11 21:29:05.362761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1be8a3b5d355'
down_revision: Union[str, Sequence[str], None] = '1d6ca9dbb698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
