"""Initial database schema

Revision ID: 1d6ca9dbb698
Revises: 
Create Date: 2025-07-11 19:57:04.207672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d6ca9dbb698'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('journal_code', sa.String(length=10), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('manuscripts_count', sa.Integer(), nullable=False),
    sa.Column('referees_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('custom_metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_logs_journal_code'), 'extraction_logs', ['journal_code'], unique=False)
    op.create_index('ix_extraction_logs_journal_date', 'extraction_logs', ['journal_code', 'started_at'], unique=False)
    op.create_table('manuscripts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('journal_code', sa.String(length=10), nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'AWAITING_REFEREE', 'AWAITING_REVISION', 'REVISED', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', name='manuscriptstatus'), nullable=False),
    sa.Column('current_round', sa.Integer(), nullable=False),
    sa.Column('submission_date', sa.DateTime(), nullable=False),
    sa.Column('editor_name', sa.String(length=200), nullable=True),
    sa.Column('associate_editor_name', sa.String(length=200), nullable=True),
    sa.Column('authors', sa.JSON(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('custom_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal_code', 'external_id', name='uix_journal_external_id')
    )
    op.create_index(op.f('ix_manuscripts_journal_code'), 'manuscripts', ['journal_code'], unique=False)
    op.create_index(op.f('ix_manuscripts_status'), 'manuscripts', ['status'], unique=False)
    op.create_index('ix_manuscripts_status_journal', 'manuscripts', ['status', 'journal_code'], unique=False)
    op.create_index('ix_manuscripts_updated', 'manuscripts', ['updated_at'], unique=False)
    op.create_table('referees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('institution', sa.String(length=500), nullable=True),
    sa.Column('expertise_areas', sa.JSON(), nullable=False),
    sa.Column('h_index', sa.Integer(), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('active_reviews', sa.Integer(), nullable=False),
    sa.Column('average_review_days', sa.Float(), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referees_email'), 'referees', ['email'], unique=True)
    op.create_index('ix_referees_reliability', 'referees', ['reliability_score'], unique=False)
    op.create_table('manuscript_referees',
    sa.Column('manuscript_id', sa.UUID(), nullable=True),
    sa.Column('referee_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.ForeignKeyConstraint(['referee_id'], ['referees.id'], )
    )
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('referee_id', sa.UUID(), nullable=False),
    sa.Column('manuscript_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('INVITED', 'ACCEPTED', 'DECLINED', 'COMPLETED', 'OVERDUE', 'CANCELLED', 'NO_RESPONSE', name='refereestatus'), nullable=False),
    sa.Column('invited_date', sa.DateTime(), nullable=False),
    sa.Column('responded_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('submitted_date', sa.DateTime(), nullable=True),
    sa.Column('quality_score', sa.Enum('EXCELLENT', 'GOOD', 'SATISFACTORY', 'POOR', 'UNACCEPTABLE', name='reviewquality'), nullable=True),
    sa.Column('report_text', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.String(length=50), nullable=True),
    sa.Column('confidence_level', sa.String(length=20), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('custom_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manuscript_id'], ['manuscripts.id'], ),
    sa.ForeignKeyConstraint(['referee_id'], ['referees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_due_date'), 'reviews', ['due_date'], unique=False)
    op.create_index('ix_reviews_manuscript_status', 'reviews', ['manuscript_id', 'status'], unique=False)
    op.create_index('ix_reviews_referee_status', 'reviews', ['referee_id', 'status'], unique=False)
    op.create_index(op.f('ix_reviews_status'), 'reviews', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_status'), table_name='reviews')
    op.drop_index('ix_reviews_referee_status', table_name='reviews')
    op.drop_index('ix_reviews_manuscript_status', table_name='reviews')
    op.drop_index(op.f('ix_reviews_due_date'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_table('manuscript_referees')
    op.drop_index('ix_referees_reliability', table_name='referees')
    op.drop_index(op.f('ix_referees_email'), table_name='referees')
    op.drop_table('referees')
    op.drop_index('ix_manuscripts_updated', table_name='manuscripts')
    op.drop_index('ix_manuscripts_status_journal', table_name='manuscripts')
    op.drop_index(op.f('ix_manuscripts_status'), table_name='manuscripts')
    op.drop_index(op.f('ix_manuscripts_journal_code'), table_name='manuscripts')
    op.drop_table('manuscripts')
    op.drop_index('ix_extraction_logs_journal_date', table_name='extraction_logs')
    op.drop_index(op.f('ix_extraction_logs_journal_code'), table_name='extraction_logs')
    op.drop_table('extraction_logs')
    # ### end Alembic commands ###
