"""Add AI analysis tables - corrected

Revision ID: 8fecb9d4f286
Revises: 1be8a3b5d355
Create Date: 2025-07-11 21:30:43.778366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fecb9d4f286'
down_revision: Union[str, Sequence[str], None] = '1be8a3b5d355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('manuscript_id', sa.String(length=100), nullable=False),
    sa.Column('journal_code', sa.String(length=10), nullable=False),
    sa.Column('analysis_timestamp', sa.DateTime(), nullable=False),
    sa.Column('processing_time_seconds', sa.Float(), nullable=False),
    sa.Column('ai_model_versions', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('pdf_path', sa.Text(), nullable=True),
    sa.Column('text_extracted', sa.Boolean(), nullable=False),
    sa.Column('analysis_quality', sa.Float(), nullable=False),
    sa.Column('desk_rejection_analysis', sa.JSON(), nullable=False),
    sa.Column('manuscript_metadata', sa.JSON(), nullable=False),
    sa.Column('human_validated', sa.Boolean(), nullable=False),
    sa.Column('validation_notes', sa.Text(), nullable=False),
    sa.Column('validation_timestamp', sa.DateTime(), nullable=True),
    sa.Column('validation_user_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_analyses_hash', 'ai_analyses', ['content_hash'], unique=False)
    op.create_index('idx_ai_analyses_manuscript_journal', 'ai_analyses', ['manuscript_id', 'journal_code'], unique=False)
    op.create_index('idx_ai_analyses_timestamp', 'ai_analyses', ['analysis_timestamp'], unique=False)
    op.create_index('idx_ai_analyses_validated', 'ai_analyses', ['human_validated'], unique=False)
    op.create_index(op.f('ix_ai_analyses_analysis_timestamp'), 'ai_analyses', ['analysis_timestamp'], unique=False)
    op.create_index(op.f('ix_ai_analyses_content_hash'), 'ai_analyses', ['content_hash'], unique=False)
    op.create_index(op.f('ix_ai_analyses_journal_code'), 'ai_analyses', ['journal_code'], unique=False)
    op.create_index(op.f('ix_ai_analyses_manuscript_id'), 'ai_analyses', ['manuscript_id'], unique=False)
    op.create_table('ai_model_performance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('evaluation_date', sa.DateTime(), nullable=False),
    sa.Column('accuracy_score', sa.Float(), nullable=True),
    sa.Column('precision_score', sa.Float(), nullable=True),
    sa.Column('recall_score', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('human_agreement_rate', sa.Float(), nullable=True),
    sa.Column('false_positive_rate', sa.Float(), nullable=True),
    sa.Column('false_negative_rate', sa.Float(), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('evaluation_method', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('evaluator_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_model_perf_accuracy', 'ai_model_performance', ['accuracy_score'], unique=False)
    op.create_index('idx_model_perf_date', 'ai_model_performance', ['evaluation_date'], unique=False)
    op.create_index('idx_model_perf_model', 'ai_model_performance', ['model_name', 'model_version'], unique=False)
    op.create_index('idx_model_perf_task', 'ai_model_performance', ['task_type'], unique=False)
    op.create_index(op.f('ix_ai_model_performance_evaluation_date'), 'ai_model_performance', ['evaluation_date'], unique=False)
    op.create_table('ai_usage_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('operation', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('processing_time_ms', sa.Float(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('journal_code', sa.String(length=10), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usage_stats_date', 'ai_usage_stats', ['date'], unique=False)
    op.create_index('idx_usage_stats_journal', 'ai_usage_stats', ['journal_code'], unique=False)
    op.create_index('idx_usage_stats_service', 'ai_usage_stats', ['service_type', 'operation'], unique=False)
    op.create_index('idx_usage_stats_success', 'ai_usage_stats', ['success'], unique=False)
    op.create_index(op.f('ix_ai_usage_stats_date'), 'ai_usage_stats', ['date'], unique=False)
    op.create_table('ai_quality_issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('issue_type', sa.Enum('TECHNICAL_ERROR', 'UNCLEAR_METHODOLOGY', 'INSUFFICIENT_NOVELTY', 'POOR_PRESENTATION', 'SCOPE_MISMATCH', 'INCOMPLETE_ANALYSIS', 'REFERENCE_ISSUES', name='qualityissuetype'), nullable=False),
    sa.Column('severity', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['ai_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quality_issue_analysis', 'ai_quality_issues', ['analysis_id'], unique=False)
    op.create_index('idx_quality_issue_severity', 'ai_quality_issues', ['severity'], unique=False)
    op.create_index('idx_quality_issue_type', 'ai_quality_issues', ['issue_type'], unique=False)
    op.create_index(op.f('ix_ai_quality_issues_analysis_id'), 'ai_quality_issues', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_ai_quality_issues_severity'), 'ai_quality_issues', ['severity'], unique=False)
    op.create_table('ai_referee_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('referee_name', sa.String(length=200), nullable=False),
    sa.Column('expertise_match', sa.Float(), nullable=False),
    sa.Column('availability_score', sa.Float(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('workload_score', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('expertise_areas', sa.JSON(), nullable=False),
    sa.Column('matching_keywords', sa.JSON(), nullable=False),
    sa.Column('contact_info', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('institution', sa.String(length=300), nullable=True),
    sa.Column('recent_publications', sa.JSON(), nullable=False),
    sa.Column('historical_response_rate', sa.Float(), nullable=True),
    sa.Column('average_review_time_days', sa.Integer(), nullable=True),
    sa.Column('review_quality_rating', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['ai_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_referee_rec_analysis', 'ai_referee_recommendations', ['analysis_id'], unique=False)
    op.create_index('idx_referee_rec_name', 'ai_referee_recommendations', ['referee_name'], unique=False)
    op.create_index('idx_referee_rec_score', 'ai_referee_recommendations', ['overall_score'], unique=False)
    op.create_index(op.f('ix_ai_referee_recommendations_analysis_id'), 'ai_referee_recommendations', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_ai_referee_recommendations_overall_score'), 'ai_referee_recommendations', ['overall_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_referee_recommendations_overall_score'), table_name='ai_referee_recommendations')
    op.drop_index(op.f('ix_ai_referee_recommendations_analysis_id'), table_name='ai_referee_recommendations')
    op.drop_index('idx_referee_rec_score', table_name='ai_referee_recommendations')
    op.drop_index('idx_referee_rec_name', table_name='ai_referee_recommendations')
    op.drop_index('idx_referee_rec_analysis', table_name='ai_referee_recommendations')
    op.drop_table('ai_referee_recommendations')
    op.drop_index(op.f('ix_ai_quality_issues_severity'), table_name='ai_quality_issues')
    op.drop_index(op.f('ix_ai_quality_issues_analysis_id'), table_name='ai_quality_issues')
    op.drop_index('idx_quality_issue_type', table_name='ai_quality_issues')
    op.drop_index('idx_quality_issue_severity', table_name='ai_quality_issues')
    op.drop_index('idx_quality_issue_analysis', table_name='ai_quality_issues')
    op.drop_table('ai_quality_issues')
    op.drop_index(op.f('ix_ai_usage_stats_date'), table_name='ai_usage_stats')
    op.drop_index('idx_usage_stats_success', table_name='ai_usage_stats')
    op.drop_index('idx_usage_stats_service', table_name='ai_usage_stats')
    op.drop_index('idx_usage_stats_journal', table_name='ai_usage_stats')
    op.drop_index('idx_usage_stats_date', table_name='ai_usage_stats')
    op.drop_table('ai_usage_stats')
    op.drop_index(op.f('ix_ai_model_performance_evaluation_date'), table_name='ai_model_performance')
    op.drop_index('idx_model_perf_task', table_name='ai_model_performance')
    op.drop_index('idx_model_perf_model', table_name='ai_model_performance')
    op.drop_index('idx_model_perf_date', table_name='ai_model_performance')
    op.drop_index('idx_model_perf_accuracy', table_name='ai_model_performance')
    op.drop_table('ai_model_performance')
    op.drop_index(op.f('ix_ai_analyses_manuscript_id'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_journal_code'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_content_hash'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_analysis_timestamp'), table_name='ai_analyses')
    op.drop_index('idx_ai_analyses_validated', table_name='ai_analyses')
    op.drop_index('idx_ai_analyses_timestamp', table_name='ai_analyses')
    op.drop_index('idx_ai_analyses_manuscript_journal', table_name='ai_analyses')
    op.drop_index('idx_ai_analyses_hash', table_name='ai_analyses')
    op.drop_table('ai_analyses')
    # ### end Alembic commands ###
