"""Create initial ECC tables

Revision ID: d75fb1bc18ea
Revises: 1a4f4345c3e1
Create Date: 2025-08-22 21:25:47.699202

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "d75fb1bc18ea"  # pragma: allowlist secret - alembic revision id
down_revision: str | Sequence[str] | None = "1a4f4345c3e1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
