#!/usr/bin/env python3
"""
Setup script for MF and MOR credentials.
This script helps configure credentials for testing MF and MOR journals.
"""

import os
import sys
import getpass
from pathlib import Path
import json
import keyring
from typing import Dict, Any

def setup_credentials_interactive():
    """Interactive setup for MF and MOR credentials"""
    print("🔐 MF and MOR Credentials Setup")
    print("=" * 40)
    print("This script will help you set up credentials for MF and MOR journals.")
    print("You can choose to:")
    print("1. Set environment variables (temporary)")
    print("2. Save to system keyring (persistent)")
    print("3. Save to .env file (persistent, file-based)")
    print()
    
    choice = input("Choose option (1-3): ").strip()
    
    credentials = {}
    
    # Get MF credentials
    print("\n📚 MF (Mathematical Finance) Credentials:")
    mf_user = input("MF Username/Email: ").strip()
    if mf_user:
        mf_pass = getpass.getpass("MF Password: ")
        credentials['MF_USER'] = mf_user
        credentials['MF_PASS'] = mf_pass
    
    # Get MOR credentials
    print("\n📊 MOR (Mathematics of Operations Research) Credentials:")
    mor_user = input("MOR Username/Email: ").strip()
    if mor_user:
        mor_pass = getpass.getpass("MOR Password: ")
        credentials['MOR_USER'] = mor_user
        credentials['MOR_PASS'] = mor_pass
    
    if not credentials:
        print("❌ No credentials provided. Exiting.")
        return False
    
    # Store credentials based on choice
    if choice == '1':
        return setup_environment_variables(credentials)
    elif choice == '2':
        return setup_keyring(credentials)
    elif choice == '3':
        return setup_env_file(credentials)
    else:
        print("❌ Invalid choice. Exiting.")
        return False

def setup_environment_variables(credentials: Dict[str, str]) -> bool:
    """Set up environment variables (temporary)"""
    print("\n🌍 Setting up environment variables...")
    
    try:
        for key, value in credentials.items():
            os.environ[key] = value
            print(f"✅ {key} set in environment")
        
        print("\n⚠️  Note: These environment variables are temporary.")
        print("They will be lost when you close this terminal session.")
        print("For persistent storage, use keyring or .env file options.")
        
        return True
        
    except Exception as e:
        print(f"❌ Error setting environment variables: {e}")
        return False

def setup_keyring(credentials: Dict[str, str]) -> bool:
    """Set up credentials in system keyring"""
    print("\n🔐 Setting up credentials in system keyring...")
    
    try:
        for key, value in credentials.items():
            keyring.set_password("editorial_scripts", key, value)
            print(f"✅ {key} saved to keyring")
        
        print("\n✅ Credentials saved to system keyring.")
        print("They will be available across sessions.")
        
        return True
        
    except Exception as e:
        print(f"❌ Error saving to keyring: {e}")
        return False

def setup_env_file(credentials: Dict[str, str]) -> bool:
    """Set up credentials in .env file"""
    print("\n📄 Setting up credentials in .env file...")
    
    try:
        env_file = Path(".env")
        
        # Read existing .env file if it exists
        existing_vars = {}
        if env_file.exists():
            with open(env_file, 'r') as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith('#') and '=' in line:
                        key, value = line.split('=', 1)
                        existing_vars[key] = value
        
        # Add new credentials
        for key, value in credentials.items():
            existing_vars[key] = value
        
        # Write updated .env file
        with open(env_file, 'w') as f:
            f.write("# Editorial Scripts Environment Variables\n")
            f.write("# Generated by setup_mf_mor_credentials.py\n")
            f.write(f"# Created: {datetime.now().isoformat()}\n\n")
            
            for key, value in existing_vars.items():
                f.write(f"{key}={value}\n")
        
        print(f"✅ Credentials saved to {env_file}")
        print("⚠️  Keep this file secure and don't commit it to version control.")
        
        return True
        
    except Exception as e:
        print(f"❌ Error saving to .env file: {e}")
        return False

def load_credentials_from_keyring() -> Dict[str, str]:
    """Load credentials from system keyring"""
    credentials = {}
    
    for key in ['MF_USER', 'MF_PASS', 'MOR_USER', 'MOR_PASS']:
        try:
            value = keyring.get_password("editorial_scripts", key)
            if value:
                credentials[key] = value
                os.environ[key] = value
        except Exception as e:
            print(f"⚠️ Could not load {key} from keyring: {e}")
    
    return credentials

def load_credentials_from_env_file() -> Dict[str, str]:
    """Load credentials from .env file"""
    credentials = {}
    env_file = Path(".env")
    
    if env_file.exists():
        try:
            with open(env_file, 'r') as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith('#') and '=' in line:
                        key, value = line.split('=', 1)
                        credentials[key] = value
                        os.environ[key] = value
        except Exception as e:
            print(f"⚠️ Could not load from .env file: {e}")
    
    return credentials

def check_credentials() -> Dict[str, Any]:
    """Check if credentials are available"""
    print("🔍 Checking for existing credentials...")
    
    status = {
        'environment_vars': {},
        'keyring': {},
        'env_file': {},
        'available_sources': []
    }
    
    # Check environment variables
    for key in ['MF_USER', 'MF_PASS', 'MOR_USER', 'MOR_PASS']:
        if os.getenv(key):
            status['environment_vars'][key] = True
        else:
            status['environment_vars'][key] = False
    
    # Check keyring
    try:
        keyring_creds = load_credentials_from_keyring()
        status['keyring'] = {key: bool(keyring_creds.get(key)) for key in ['MF_USER', 'MF_PASS', 'MOR_USER', 'MOR_PASS']}
        if keyring_creds:
            status['available_sources'].append('keyring')
    except Exception as e:
        status['keyring'] = {'error': str(e)}
    
    # Check .env file
    try:
        env_creds = load_credentials_from_env_file()
        status['env_file'] = {key: bool(env_creds.get(key)) for key in ['MF_USER', 'MF_PASS', 'MOR_USER', 'MOR_PASS']}
        if env_creds:
            status['available_sources'].append('env_file')
    except Exception as e:
        status['env_file'] = {'error': str(e)}
    
    return status

def load_all_credentials():
    """Load credentials from all available sources"""
    print("📥 Loading credentials from all sources...")
    
    # Load from keyring
    keyring_creds = load_credentials_from_keyring()
    print(f"🔐 Loaded {len(keyring_creds)} credentials from keyring")
    
    # Load from .env file
    env_creds = load_credentials_from_env_file()
    print(f"📄 Loaded {len(env_creds)} credentials from .env file")
    
    # Check what's available
    total_found = 0
    for key in ['MF_USER', 'MF_PASS', 'MOR_USER', 'MOR_PASS']:
        if os.getenv(key):
            total_found += 1
            print(f"✅ {key} is available")
        else:
            print(f"❌ {key} is missing")
    
    print(f"\n📊 Total credentials found: {total_found}/4")
    
    return total_found >= 2  # Need at least one complete set

def main():
    """Main credential setup function"""
    print("🔐 MF and MOR Credentials Manager")
    print("=" * 50)
    
    if len(sys.argv) > 1 and sys.argv[1] == '--check':
        # Just check existing credentials
        status = check_credentials()
        
        print("\n📊 Credential Status:")
        print(f"Environment Variables: {sum(status['environment_vars'].values())}/4")
        print(f"Keyring: {sum(v for v in status['keyring'].values() if isinstance(v, bool))}/4")
        print(f"Env File: {sum(v for v in status['env_file'].values() if isinstance(v, bool))}/4")
        print(f"Available Sources: {', '.join(status['available_sources'])}")
        
        return 0
    
    if len(sys.argv) > 1 and sys.argv[1] == '--load':
        # Load all available credentials
        success = load_all_credentials()
        if success:
            print("\n✅ Credentials loaded successfully!")
            return 0
        else:
            print("\n❌ Insufficient credentials available.")
            print("Run without --load to set up credentials.")
            return 1
    
    # Interactive setup
    try:
        success = setup_credentials_interactive()
        if success:
            print("\n✅ Credentials setup completed!")
            print("You can now run the MF and MOR debugging script.")
            return 0
        else:
            print("\n❌ Credential setup failed.")
            return 1
            
    except KeyboardInterrupt:
        print("\n⚠️ Setup interrupted by user.")
        return 1
    except Exception as e:
        print(f"\n❌ Setup failed: {e}")
        return 1

if __name__ == "__main__":
    from datetime import datetime
    exit(main())